### PR TITLE
Add logic to compile the submodule libsnark

### PR DESCRIPTION
**Pull request by shaanrockz**
## Description
Added logic to compile the submodule libsnark. Two different ways to compile based on OS (Linux and MacOS)

## Type of change
Added building snippet for Linux and MacOS based system

Please mark options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

### CODE REVIEW

**Comment by shaanrockz** [comment]
Sorry for taking long, I had a hard time compiling libsnark in MacOS

**Comment by gargarchit** [comment]
Yes, I tried with git submodule update --init --recursive is  before cmake and it works, @shaanrockz please add that

**Comment by gargarchit** [comment]
Fix #19

**Comment by shaanrockz** [comment]
> On Linux (Debian 10 to be precise) the following deps were mentioned: libcrypto and libprocps
> 
> * The commands for Linux probably should include the installation of libcrypto and libprocps
> * The build on Linux fails unless the command `git submodule update --init --recursive`  is executed before cmake ..

Yes. Corrected.

**Comment by codeboy5** [comment]
Hi @shaanrockz, I am having issues compiling it on macOS. 
We need to just follow the steps in the README right?

**Comment by Benardi** [comment]
It might be helpful to divide it into two different scripts for the sake of convenience

**Comment by gargarchit** [comment]
Yes we can create 2 Build.sh, one for Linux and one for MacOS

**Comment by codeboy5** [comment]
Can someone confirm this works on Mac, I’m having issues.
It works perfectly on Linux

**Pull request merged**
